# 应用服务 WEB 访问端口
server:
  port: 8081
  servlet:
    context-path: /myApp
management:
  endpoints:
    web:
      exposure:
        include: "*"   #放行数据
  endpoint:
    prometheus:
      enabled: true  #开启普罗米修斯，对上面放行的数据进行格式转换
    health:
      show-details: always #展示服务监控更多细节
  metrics:
    export:
      prometheus:
        enabled: true #上面的指标允许被导出

#数据库连接
spring:
  application:
    name: my-app
  datasource:
    druid:
      username: root
      password: 662313
      url: jdbc:mysql://localhost:3306/my_app?useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-circular-references: true #允许自注入，默认false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #swagger3需要配置，因为springfox基于AntPathMatcher匹配路径

  #reids配置
  redis:
    database: 1
    host: localhost
    port: 6379
    # redisson配置
    redisson:
      # 数据库编号
      database: 1
      # 节点地址
      address: redis://localhost:6379

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/yumoxuan/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true




